name: 📗 Documentation Build

on:
  push:
    branches:
      - docs
    paths:
    - 'docs/'
    - '.github/workflows/documentation.yml'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
            cd docs
            npm ci
            npm run docs:build

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/docs'
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
